### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument on jetson xavier nx

### ISSUE THREAD

**Issue by dchssk** [haotian-liu/yolact_edge#229]
Hi,

Thank you for developing this amazing tool.
I am currently using a Jetson Xavier NX but we have some problems during the INT8 evaluation.

**Full logs**
```
# python3 eval.py --config=yolact_edge_config --trained_model=/share/yolact_edge_54_800000.pth  --score_threshold=0.3 --top_k=100  --image=/share/test.jpg 
[12/20 13:32:31 yolact.eval]: Loading model...
[12/20 13:32:41 yolact.eval]: Model loaded.
[12/20 13:32:41 yolact.eval]: Converting to TensorRT...
Traceback (most recent call last):
  File "eval.py", line 1275, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/share/yolact_edge/yolact_edge/utils/tensorrt.py", line 106, in convert_to_tensorrt
    "moving_statistics": None
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/share/yolact_edge/yolact_edge/yolact.py", line 1621, in forward
    outs = self.backbone(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/share/yolact_edge/yolact_edge/backbone.py", line 121, in forward
    x = self.maxpool(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/pooling.py", line 164, in forward
    self.return_indices)
  File "/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py", line 365, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 659, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA error: invalid configuration argument
```

**Environment:**
 - NVIDIA ® Jetson Xavier™ NX
 - nvidia-l4t-core 32.5.1
 - TensorRT : 7.1.3
 - CUDA version : 10.2

**Comment by dchssk** [comment]
Sorry, I solved it myself.

https://github.com/haotian-liu/yolact_edge/issues/45#issuecomment-771430980
As you can see here, I reduced "torch2trt_max_calibration_images" to something like 5 and it works fine!
