### ISSUE TITLE
problem with installing a few things using the docker env

### ISSUE THREAD

**Issue by riririririi** [haotian-liu/yolact_edge#231]
**Describe the bug**
when i run `docker build --build-arg USER_ID=$UID -t yolact_edge_image .` it returns these errors:
E: Unable to locate package libnvinfer7
E: Unable to locate package libnvonnxparsers7
E: Unable to locate package libnvparsers7
E: Unable to locate package libnvinfer-plugin7
E: Version '7.2.3-1+cuda11.0' for 'libnvinfer-dev' was not found
E: Version '7.2.3-1+cuda11.0' for 'libnvonnxparsers-dev' was not found
E: Version '7.2.3-1+cuda11.0' for 'libnvparsers-dev' was not found
E: Version '7.2.3-1+cuda11.0' for 'libnvinfer-plugin-dev' was not found
E: Version '7.2.3-1+cuda11.0' for 'python3-libnvinfer' was not found
The command '/bin/sh -c apt-get update &&     apt-get install -y libnvinfer7=${version} libnvonnxparsers7=${version} libnvparsers7=${version} libnvinfer-plugin7=${version} libnvinfer-dev=${version} libnvonnxparsers-dev=${version} libnvparsers-dev=${version} libnvinfer-plugin-dev=${version} python3-libnvinfer=${version} &&     apt-mark hold libnvinfer7 libnvonnxparsers7 libnvparsers7 libnvinfer-plugin7 libnvinfer-dev libnvonnxparsers-dev libnvparsers-dev libnvinfer-plugin-dev python3-libnvinfer' returned a non-zero code: 100

**To Reproduce**
running `docker build --build-arg USER_ID=$UID -t yolact_edge_image .` in the yolact_edge/docker folder 

**Expected behavior**
the docker image should get assembled

**Environment:**
 - OS: [Ubuntu 22.04]
 - GPU: [RTX 3060 Ti]
 - CUDA Version [e.g. 12]

**Comment by HwanWoongLee** [comment]
i have the same problem...
Did you solve the problem?

**Comment by jimmyjommy** [comment]
I got around it by changing all of the libv versions from 7 to 8, and changing the ARG version on line 14 to 8.0.0-1

**Comment by AvinoamBr** [comment]
I've encountered same issue and solved by setting:
ARG version="8.5.3-1+cuda11.8"

**Comment by hiepdtx** [comment]
LINE 14: change ARG version="7.2.3-1+cuda11.0" to ARG version="8.0.0-1+cuda11.0"
LINE 15: change all of version "7" to "8"
You can refer the version of "libnvinfer8", "libnvonnxparsers8" corresponding to CUDA and ubuntu version at https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
(Should use consistent CUDA version for Pytorch and TensorRT, for example)

**Comment by hiepbk** [comment]
LINE 14: change ARG version="7.2.3-1+cuda11.0" to ARG version="8.0.0-1+cuda11.0"
LINE 15: change all of version "7" to "8"
You can refer the version of "libnvinfer8", "libnvonnxparsers8" corresponding to CUDA and ubuntu version at https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
(Should use consistent CUDA version for Pytorch and TensorRT, for example)

**Comment by domef** [comment]
> LINE 14: change ARG version="7.2.3-1+cuda11.0" to ARG version="8.0.0-1+cuda11.0" LINE 15: change all of version "7" to "8" You can refer the version of "libnvinfer8", "libnvonnxparsers8" corresponding to CUDA and ubuntu version at https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ (Should use consistent CUDA version for Pytorch and TensorRT, for example)

This works for me, I could create the docker image. I hope I can also train the model.

I had only one problem with TensorRT, fortunately I don't need it so I just commented that part:
```bash
 => ERROR [15/19] RUN python setup.py install --plugins --user                                                                                                             0.9s 
------                                                                                                                                                                          
 > [15/19] RUN python setup.py install --plugins --user:                                                                                                                        
0.838 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'                                                                                                               
0.838 /home/appuser/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
0.838   return torch._C._cuda_getDeviceCount() > 0
0.838 Traceback (most recent call last):
0.838   File "setup.py", line 6, in <module>
0.838     from packaging import version
0.838 ModuleNotFoundError: No module named 'packaging'
------
Dockerfile:41
--------------------
  39 |     RUN git clone https://github.com/NVIDIA-AI-IOT/torch2trt
  40 |     WORKDIR /home/${USER}/torch2trt
  41 | >>> RUN python setup.py install --plugins --user
  42 |     
  43 |     WORKDIR /home/${USER}
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py install --plugins --user" did not complete successfully: exit code: 1
```
